included:
  - Sources
  - Tests

excluded:
  - .build

line_length:
  warning: 120
  error: 160

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2

opt_in_rules:
  - explicit_init
  - redundant_nil_coalescing
  - sorted_imports
