name: HomeScreenOptimizerApp
options:
  bundleIdPrefix: com.davidroh
  deploymentTarget:
    iOS: "17.0"
configs:
  Debug: debug
  Release: release
packages:
  HomeScreenOptimizer:
    path: .
settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: ""
targets:
  HomeScreenOptimizeriOS:
    type: application
    platform: iOS
    sources:
      - App/Sources
    info:
      path: App/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.davidroh.homescreenoptimizer
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        CODE_SIGN_ENTITLEMENTS: App/HomeScreenOptimizeriOS.entitlements
        INFOPLIST_KEY_CFBundleDisplayName: HomeScreenOptimizer
        GENERATE_INFOPLIST_FILE: false
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - target: HomeScreenUsageReportExtension
        embed: true
      - package: HomeScreenOptimizer
        product: Core
      - package: HomeScreenOptimizer
        product: Ingestion
      - package: HomeScreenOptimizer
        product: Profiles
      - package: HomeScreenOptimizer
        product: Usage
      - package: HomeScreenOptimizer
        product: Optimizer
      - package: HomeScreenOptimizer
        product: Guide
      - package: HomeScreenOptimizer
        product: Simulation
      - package: HomeScreenOptimizer
        product: Privacy

  HomeScreenUsageReportExtension:
    type: extensionkit-extension
    platform: iOS
    sources:
      - App/ScreenTimeReportExtension
    info:
      path: App/ScreenTimeReportExtension/Info.plist
      properties:
        EXAppExtensionAttributes:
          EXExtensionPointIdentifier: com.apple.deviceactivityui.report-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.davidroh.homescreenoptimizer.usagereport
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.10
        SWIFT_STRICT_CONCURRENCY: minimal
        CODE_SIGN_ENTITLEMENTS: App/ScreenTimeReportExtension/HomeScreenUsageReportExtension.entitlements
        GENERATE_INFOPLIST_FILE: false
    dependencies:
      - package: HomeScreenOptimizer
        product: Ingestion

  HomeScreenOptimizeriOSTests:
    type: bundle.unit-test
    platform: iOS
    hostApplication: HomeScreenOptimizeriOS
    sources:
      - App/Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: HomeScreenOptimizeriOS

schemes:
  HomeScreenOptimizeriOS:
    build:
      targets:
        HomeScreenOptimizeriOS: all
    test:
      targets:
        - HomeScreenOptimizeriOSTests
    run:
      config: Debug
